"use client";
import {useEffect,useMemo,useState} from "react";
import * as XLSX from "xlsx";
import appPackage from "../../package.json";
import styles from "./page.module.css";

type Row=Record<string,unknown>;
type Order={number:string;containers:string[];client:string;route:string;departure:string;arrival:string};
const value=(row:Row|undefined,...keys:string[])=>{for(const key of keys){const result=String(row?.[key]??"").trim();if(result)return result;}return "";};
const container=(row:Row)=>{for(const cell of Object.values(row)){const match=String(cell??"").toUpperCase().match(/[A-ZА-Я]{4}\d{7}/);if(match)return match[0];}return "";};
const read=async(response:Response,sheet:string)=>{if(!response.ok)throw new Error("Сохранённый реестр TMS не найден");const workbook=XLSX.read(await response.arrayBuffer(),{type:"array",cellDates:true});const name=workbook.SheetNames.includes(sheet)?sheet:workbook.SheetNames[0];return XLSX.utils.sheet_to_json<Row>(workbook.Sheets[name],{defval:""});};

export default function ForwardingOrders(){
  const [orders,setOrders]=useState<Order[]>([]),[query,setQuery]=useState(""),[loading,setLoading]=useState(true),[busy,setBusy]=useState(""),[message,setMessage]=useState("Загружаем реестр заказов…"),[signer,setSigner]=useState("Иванов Иван Иванович");
  useEffect(()=>{void Promise.all([fetch("/api/source-cache?kind=cargo").then(r=>read(r,"OPERATION_UNIT")),fetch("/api/source-cache?kind=auto").then(r=>read(r,"OPERATION_SUB_DOC"))]).then(([cargo,auto])=>{const autoIndex=new Map(auto.map(row=>[container(row),row]).filter(([key])=>key));const grouped=new Map<string,Order>();for(const row of cargo){const number=value(row,"Номер заказа");const key=container(row);if(!number||!key)continue;const trip=autoIndex.get(key);const current=grouped.get(number)||{number,containers:[],client:value(row,"Клиент","Заказчик"),route:value(trip,"Маршрут"),departure:value(trip,"Плановая дата отправления"),arrival:value(trip,"Плановая дата прибытия","Последняя план дата прибытия","ETA (план дата прибытия)")};if(!current.containers.includes(key))current.containers.push(key);grouped.set(number,current);}const result=[...grouped.values()];setOrders(result);setMessage(result.length?`Загружено заказов: ${result.length}. Контейнеров: ${result.reduce((sum,item)=>sum+item.containers.length,0)}`:"В сохранённом реестре ещё нет номера заказа. Обновите данные из TMS в разделе «Создание документов».");}).catch(error=>setMessage(error instanceof Error?error.message:"Не удалось загрузить заказы")).finally(()=>setLoading(false));},[]);
  const filtered=useMemo(()=>{const needle=query.trim().toLocaleLowerCase("ru-RU");return orders.filter(item=>!needle||[item.number,item.client,item.route,...item.containers].some(text=>text.toLocaleLowerCase("ru-RU").includes(needle)));},[orders,query]);
  const generate=async(order:Order)=>{if(!signer.trim()){setMessage("Укажите ФИО подписанта клиента");return;}setBusy(order.number);setMessage(`Формируем поручение по заказу ${order.number}…`);try{const response=await fetch("/api/forwarding-order",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({orderNumber:order.number,containers:order.containers,user:"Алексеев Михаил Геннадьевич",signer})});const result=await response.json();if(!response.ok)throw new Error(result.error||"Не удалось сформировать поручение");const bytes=Uint8Array.from(atob(result.content),(char)=>char.charCodeAt(0));const link=document.createElement("a");link.href=URL.createObjectURL(new Blob([bytes],{type:"application/xml"}));link.download=result.filename;link.click();URL.revokeObjectURL(link.href);setMessage(`XML по заказу ${order.number} сформирован: ${order.containers.length} контейнеров`);}catch(error){setMessage(error instanceof Error?error.message:"Ошибка формирования");}finally{setBusy("");}};
  return <main className={styles.shell}><header className={styles.topbar}><div>А</div><strong>Создание ЭПД <small>версия {appPackage.version}</small></strong><nav><a href="/workspace">Создание документов</a><a className={styles.active} href="/forwarding-orders">Поручения клиентам</a><a href="/control">Контроль подписания</a><a href="/statistics">Статистика</a><a href="/edo-settings">Настройки ID ЭДО</a></nav></header><section className={styles.content}><header className={styles.heading}><div><small>РЕЕСТР ЗАКАЗОВ</small><h1>Поручения клиентам</h1><p>Один заказ может содержать несколько контейнеров. Формируется один XML Т1 на заказ.</p></div></header><section className={styles.toolbar}><label><span>Подписант со стороны клиента *</span><input value={signer} onChange={event=>setSigner(event.target.value)} placeholder="Фамилия Имя Отчество"/></label><label><span>Поиск по заказам</span><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Номер заказа, клиент или контейнер"/></label></section><p className={styles.message}>{message}</p><section className={styles.table}><table><thead><tr><th>Заказ</th><th>Контейнеры</th><th>Клиент</th><th>Маршрут</th><th>Плановые даты</th><th>XML поручения</th></tr></thead><tbody>{filtered.map(order=><tr key={order.number}><td><strong>{order.number}</strong></td><td><strong>{order.containers.length}</strong><small>{order.containers.join(", ")}</small></td><td>{order.client||"Не указан"}</td><td>{order.route||"Не указан"}</td><td><small>{order.departure||"—"}</small><small>{order.arrival||"—"}</small></td><td><button disabled={Boolean(busy)||!signer.trim()} onClick={()=>void generate(order)}>{busy===order.number?"Формируем…":"Сформировать и скачать"}</button></td></tr>)}{!loading&&!filtered.length&&<tr><td colSpan={6} className={styles.empty}>Заказы не найдены</td></tr>}</tbody></table></section></section></main>;
}
