"use client";
import {useEffect,useState} from "react";
import appPackage from "../../package.json";
import styles from "./page.module.css";

type Order={number:string;containers:string[];client:string;route:string;departure:string;arrival:string};

export default function ForwardingOrders(){
  const [orders,setOrders]=useState<Order[]>([]),[query,setQuery]=useState(""),[loading,setLoading]=useState(true),[busy,setBusy]=useState(""),[message,setMessage]=useState("Загружаем заказы…");
  const signer="Иванов Иван Иванович";
  useEffect(()=>{const timeout=window.setTimeout(()=>{setLoading(true);void fetch(`/api/orders/search?limit=20&query=${encodeURIComponent(query.trim())}`,{cache:"no-store"}).then(async response=>{const result=await response.json();if(!response.ok)throw new Error(result.error||"Не удалось загрузить заказы");setOrders(result.items||[]);setMessage(result.total?`Показано ${Math.min(20,result.total)} из ${result.total} заказов`:(query.trim()?"Заказы по запросу не найдены":"В сохранённом реестре ещё нет номера заказа. Обновите данные из TMS в разделе «Создание документов»."));}).catch(error=>setMessage(error instanceof Error?error.message:"Не удалось загрузить заказы")).finally(()=>setLoading(false));},query.trim()?300:0);return()=>window.clearTimeout(timeout);},[query]);
  const generate=async(order:Order)=>{setBusy(order.number);setMessage(`Формируем поручение по заказу ${order.number}…`);try{const response=await fetch("/api/forwarding-order",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({orderNumber:order.number,containers:order.containers,user:"Алексеев Михаил Геннадьевич",signer})});const result=await response.json();if(!response.ok)throw new Error(result.error||"Не удалось сформировать поручение");const bytes=Uint8Array.from(atob(result.content),(char)=>char.charCodeAt(0));const link=document.createElement("a");link.href=URL.createObjectURL(new Blob([bytes],{type:"application/xml"}));link.download=result.filename;link.click();URL.revokeObjectURL(link.href);setMessage(`XML по заказу ${order.number} сформирован: ${order.containers.length} контейнеров`);}catch(error){setMessage(error instanceof Error?error.message:"Ошибка формирования");}finally{setBusy("");}};
  return <main className={styles.shell}><header className={styles.topbar}><div>А</div><strong>Создание ЭПД <small>версия {appPackage.version}</small></strong><nav><a href="/workspace">Создание документов</a><a className={styles.active} href="/forwarding-orders">Поручения клиентам</a><a href="/control">Контроль подписания</a><a href="/statistics">Статистика</a><a href="/edo-settings">Настройки ID ЭДО</a></nav></header><section className={styles.content}><header className={styles.heading}><div><small>РЕЕСТР ЗАКАЗОВ</small><h1>Поручения клиентам</h1><p>Один заказ может содержать несколько контейнеров. Формируется один XML Т1 на заказ.</p></div></header><section className={styles.toolbar}><label><span>Поиск по заказам</span><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Номер заказа, клиент или контейнер"/></label></section><p className={styles.message}>{message}</p><section className={styles.table}><table><thead><tr><th>Заказ</th><th>Контейнеры</th><th>Клиент</th><th>Маршрут</th><th>Плановые даты</th><th>XML поручения</th></tr></thead><tbody>{orders.map(order=><tr key={order.number}><td><strong>{order.number}</strong></td><td><strong>{order.containers.length}</strong><small>{order.containers.join(", ")}</small></td><td>{order.client||"Не указан"}</td><td>{order.route||"Не указан"}</td><td><small>{order.departure||"—"}</small><small>{order.arrival||"—"}</small></td><td><button disabled={Boolean(busy)} onClick={()=>void generate(order)}>{busy===order.number?"Формируем…":"Сформировать и скачать"}</button></td></tr>)}{!loading&&!orders.length&&<tr><td colSpan={6} className={styles.empty}>Заказы не найдены</td></tr>}</tbody></table></section></section></main>;
}
