"use client";
import {useEffect,useMemo,useState} from "react";
import {CertificateOption,listCertificates,signDetached} from "./cades";
import styles from "./revoke-dialog.module.css";

type RevokeItem={number:string;messageId:string;entityId:string;sourceMessageId:string;sourceEntityId:string};
type PowerOfAttorneyOption={fullId:{RegistrationNumber:string;IssuerInn:string;RepresentativeInn:string};isDefault:boolean;issuerName:string;representativeName:string;validFrom:unknown;validTo:unknown};
type Props={item:RevokeItem;defaultSigner:string;onClose:()=>void;onSent:()=>void|Promise<void>};
const bytesToBase64=(bytes:Uint8Array)=>{let result="";for(let offset=0;offset<bytes.length;offset+=0x8000)result+=String.fromCharCode(...bytes.subarray(offset,offset+0x8000));return btoa(result);};

export default function RevokeDialog({item,defaultSigner,onClose,onSent}:Props){
  const [certificates,setCertificates]=useState<CertificateOption[]>([]);const [powers,setPowers]=useState<PowerOfAttorneyOption[]>([]);const [powerId,setPowerId]=useState("");const [signer,setSigner]=useState(defaultSigner);const [thumbprint,setThumbprint]=useState("");const [reason,setReason]=useState("");const [terminationDate,setTerminationDate]=useState(new Date().toISOString().slice(0,10));const [actualExpenses,setActualExpenses]=useState("");const [cargoInstructions,setCargoInstructions]=useState("");const [busy,setBusy]=useState(true);const [error,setError]=useState("");
  useEffect(()=>{void Promise.all([listCertificates(),fetch("/api/kontur/powers-of-attorney",{cache:"no-store"}).then(async response=>{const value=await response.json();if(!response.ok)throw new Error(value.error||"Не удалось получить МЧД");return value.items as PowerOfAttorneyOption[];})]).then(([certs,attorneys])=>{setCertificates(certs);setPowers(attorneys);if(certs[0]){setSigner(certs[0].displayName);setThumbprint(certs[0].thumbprint);}const preferred=attorneys.find(item=>item.isDefault)||attorneys[0];if(preferred)setPowerId(preferred.fullId.RegistrationNumber);}).catch(value=>setError(value instanceof Error?value.message:"Не удалось получить сертификаты и МЧД")).finally(()=>setBusy(false));},[]);
  const signers=useMemo(()=>[...new Set(certificates.map(item=>item.displayName))],[certificates]);const signerCertificates=certificates.filter(item=>item.displayName===signer);const selected=certificates.find(item=>item.thumbprint===thumbprint);const selectedPower=powers.find(item=>item.fullId.RegistrationNumber===powerId);
  const changeSigner=(value:string)=>{setSigner(value);setThumbprint(certificates.find(item=>item.displayName===value)?.thumbprint||"");};
  const submit=async()=>{if(!reason.trim()||!terminationDate||!selected)return;const [signerLastName,signerFirstName,...middle]=signer.trim().split(/\s+/);if(!signerLastName||!signerFirstName){setError("В сертификате не определены фамилия и имя подписанта");return;}if(!window.confirm(`Подписать и отправить отзыв поручения №${item.number} в Диадок? После отправки отменить действие нельзя.`))return;setBusy(true);setError("");try{const generated=await fetch("/api/kontur/forwarding-revoke",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({messageId:item.messageId,entityId:item.entityId,sourceMessageId:item.sourceMessageId,sourceEntityId:item.sourceEntityId,reason,terminationDate,actualExpenses,cargoInstructions,signerLastName,signerFirstName,signerMiddleName:middle.join(" ")})});if(!generated.ok){const value=await generated.json();throw new Error(value.error||"Не удалось сформировать Т3");}const contentBase64=bytesToBase64(new Uint8Array(await generated.arrayBuffer()));const signatureBase64=await signDetached(contentBase64,selected.thumbprint);const sent=await fetch("/api/kontur/forwarding-revoke/send",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({messageId:item.messageId,parentEntityId:item.sourceEntityId||item.entityId,contentBase64,signatureBase64,powerOfAttorney:selectedPower?{fullId:selectedPower.fullId}:null})});const result=await sent.json();if(!sent.ok)throw new Error(result.error||"Не удалось отправить Т3");await onSent();onClose();window.alert("Отзыв подписан и отправлен в Диадок");}catch(value){setError(value instanceof Error?value.message:"Не удалось подписать и отправить Т3");}finally{setBusy(false);}};
  return <div className={styles.backdrop} role="presentation"><section className={styles.dialog} role="dialog" aria-modal="true" aria-labelledby="revoke-title"><header className={styles.header}><div><h2 id="revoke-title">Отзыв поручения №{item.number}</h2><p>Т3 будет подписан выбранным сертификатом и отправлен в Диадок</p></div><button className={styles.close} onClick={onClose} aria-label="Закрыть">×</button></header><div className={styles.form}><label className={`${styles.field} ${styles.wide}`}><span>Подписант</span><select value={signer} onChange={event=>changeSigner(event.target.value)} disabled={busy}>{signers.map(value=><option key={value}>{value}</option>)}</select></label><label className={`${styles.field} ${styles.wide}`}><span>Сертификат</span><select value={thumbprint} onChange={event=>setThumbprint(event.target.value)} disabled={busy}>{signerCertificates.map(item=><option value={item.thumbprint} key={item.thumbprint}>{item.organization?`${item.organization} · `:""}действует до {item.validTo}</option>)}</select>{selected&&<small className={styles.certificate}>Отпечаток: …{selected.thumbprint.slice(-12)}</small>}</label><label className={`${styles.field} ${styles.wide}`}><span>МЧД</span><select value={powerId} onChange={event=>setPowerId(event.target.value)} disabled={busy}><option value="">Без МЧД</option>{powers.map(item=><option value={item.fullId.RegistrationNumber} key={item.fullId.RegistrationNumber}>{item.issuerName} → {item.representativeName}{item.isDefault?" · по умолчанию":""} · …{item.fullId.RegistrationNumber.slice(-8)}</option>)}</select></label><label className={`${styles.field} ${styles.wide}`}><span>Причина отзыва *</span><textarea value={reason} onChange={event=>setReason(event.target.value)}/></label><label className={styles.field}><span>Дата прекращения *</span><input type="date" value={terminationDate} onChange={event=>setTerminationDate(event.target.value)}/></label><label className={styles.field}><span>Фактические расходы, руб.</span><input inputMode="decimal" value={actualExpenses} onChange={event=>setActualExpenses(event.target.value)} placeholder="0.00"/></label><label className={`${styles.field} ${styles.wide}`}><span>Указания по грузу</span><textarea value={cargoInstructions} onChange={event=>setCargoInstructions(event.target.value)} placeholder="Необязательно"/></label>{error&&<div className={styles.error} role="alert">{error}</div>}</div><footer className={styles.footer}><button className={styles.cancel} onClick={onClose}>Отмена</button><button className={styles.send} onClick={()=>void submit()} disabled={busy||!reason.trim()||!terminationDate||!selected}>{busy?"Получаем сертификаты…":"Подписать и отправить"}</button></footer></section></div>;
}
