"use client";
import {useEffect,useMemo,useState} from "react";
import styles from "./edo-settings.module.css";
import appPackage from "../../package.json";

type History={count:number;lastSignedAt:string;documentNumber:string};
type Option={id:string;operator:string;boxId:string;history:History|null};
type Party={name:string;inn:string;kpp:string;key:string;selectedId:string;selectionSource:"manual"|"history"|"automatic"|"unresolved";selectedBy:string;selectedAt:string;options:Option[]};

export default function EdoSettings(){
  const [parties,setParties]=useState<Party[]>([]),[loading,setLoading]=useState(true),[query,setQuery]=useState(""),[message,setMessage]=useState("Ищем контрагентов с несколькими операторами…");
  const [drafts,setDrafts]=useState<Record<string,string>>({}),[saving,setSaving]=useState("");
  const load=async()=>{setLoading(true);try{const response=await fetch("/api/edo-directory",{cache:"no-store"});const result=await response.json();if(!response.ok)throw new Error(result.error);setParties(result.parties||[]);setMessage(`Контрагентов с несколькими операторами: ${(result.parties||[]).length}`);}catch(error){setMessage(error instanceof Error?error.message:"Не удалось загрузить справочник");}finally{setLoading(false);}};
  useEffect(()=>{void load();},[]);
  const filtered=useMemo(()=>{const value=query.trim().toLocaleLowerCase("ru-RU");return !value?parties:parties.filter(party=>[party.name,party.inn,party.kpp,...party.options.flatMap(option=>[option.operator,option.id])].some(item=>String(item||"").toLocaleLowerCase("ru-RU").includes(value)));},[parties,query]);
  const save=async(party:Party)=>{const participantId=drafts[party.key]||party.selectedId;if(!participantId)return;setSaving(party.key);try{const response=await fetch("/api/edo-preference",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({key:party.key,participantId,selectedBy:"Справочник настроек"})});const result=await response.json();if(!response.ok)throw new Error(result.error);setParties(current=>current.map(item=>item.key===party.key?{...item,selectedId:participantId,selectionSource:"manual",selectedBy:"Справочник настроек",selectedAt:result.preference.selectedAt}:item));setDrafts(current=>{const next={...current};delete next[party.key];return next;});setMessage(`Выбор для ${party.name} сохранён отдельно и не изменится при обновлении справочников.`);}catch(error){setMessage(error instanceof Error?error.message:"Не удалось сохранить выбор");}finally{setSaving("");}};
  return <main className={styles.shell}>
    <header className={styles.topbar}><div>А</div><strong>Создание ЭПД <small>версия {appPackage.version}</small></strong><nav><a href="/workspace">Создание документов</a><a href="/forwarding-orders">Поручения клиентам</a><a href="/control">Контроль подписания</a><a href="/statistics">Статистика</a><a className={styles.active} href="/edo-settings">Настройки ID ЭДО</a></nav></header>
    <section className={styles.content}><header className={styles.heading}><div><small>СПРАВОЧНИК</small><h1>Настройки ID для ЭПД</h1><p>Только контрагенты с несколькими операторами. Выберите нужный вариант и обязательно нажмите «Сохранить выбор».</p></div><button onClick={()=>void load()} disabled={loading}>{loading?"Проверяем…":"Обновить историю"}</button></header>
      <div className={styles.toolbar}><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Название, ИНН, оператор или ID ЭДО"/><span>{message}</span></div>
      <div className={styles.list}>{filtered.map(party=>{const chosen=drafts[party.key]??party.selectedId;const changed=Boolean(drafts[party.key]&&drafts[party.key]!==party.selectedId);return <article key={party.key}><header><div><h2>{party.name}</h2><p>ИНН {party.inn}{party.kpp?` · КПП ${party.kpp}`:""}</p></div><b className={styles[party.selectionSource]}>{changed?"Выбор не сохранён":party.selectionSource==="manual"?"Закреплено вручную":party.selectionSource==="history"?"Подтверждено подписью":party.selectionSource==="automatic"?"Единственный ID":"Нужно выбрать"}</b></header><div className={styles.options}>{party.options.map(option=><label key={option.id} className={chosen===option.id?styles.selected:""}><input type="radio" name={party.key} checked={chosen===option.id} onChange={()=>setDrafts(current=>({...current,[party.key]:option.id}))}/><span><strong>{option.operator}</strong><small>{option.id}</small></span><em>{option.history?`Подписанных документов: ${option.history.count}`:"Подтверждённых подписей нет"}</em></label>)}</div>{party.options.length>1&&<footer className={styles.saveBar}><span>{changed?"Новый оператор выбран. Нажмите «Сохранить выбор».":"Сохранённый выбор не перезаписывается обновлениями."}</span><button disabled={!chosen||!changed||saving===party.key} onClick={()=>void save(party)}>{saving===party.key?"Сохраняем…":"Сохранить выбор"}</button></footer>}</article>;})}</div>
      {!loading&&!filtered.length&&<p className={styles.empty}>Ничего не найдено</p>}
    </section>
  </main>;
}
